### ISSUE TITLE
Feature request: POST vs GET

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#16]
Would it be feasible to add a command line switch like `-post` so that it sends POST requests instead of GET requests? Thank you.

**Comment by proabiral** [comment]
Hey, I have been working on this lately. Will probably publish it on first week of September.

**Comment by proabiral** [comment]
Hi @geeknik ,
I have added the feature to support http method and body. 
Please check out this [commit](https://github.com/proabiral/inception/commit/655707ebf0efc52cf59273c18c8e4c5442a52856).

**Comment by geeknik** [comment]
There is a good possibility I'm doing something wrong, but I'm not seeing any requests against my host if I use POST, PUT or DELETE.

**Comment by proabiral** [comment]
Hi @geeknik ,

Few things you might be doing wrong  :
1) Since the code is not pushed to master branch yet. You need to pull it from beta branch and run from there. https://github.com/proabiral/inception/tree/beta
2) Methods are not taken from command line argument but taken from provider.json. The provider needs to be created from providerCreate.html [here](https://github.com/proabiral/inception/blob/beta/providerCreate.html). The old one [here](https://proabiral.github.io/inception/providerCreate.html) is not yet updated.

Please feel free to let me know if there are any trouble.

**Comment by geeknik** [comment]
Yes, yes. 

Here is the provider.json that I created just as a test to see how the request looked on a local server of mine. 

```
[
    {
        "vulnerability": "test",
        "method": "POST",
        "color": "red",
        "body": "{test:1}",
        "endpoint": [
            "/"
        ],
        "headers": [
            [
                "test",
                "1"
            ]
        ],
        "checkIn": "responseBody",
        "checkFor": "test:1"
    }
]
```
No request appears in /var/log/nginx/access.log or /var/log/nginx/error.log

**Comment by proabiral** [comment]
The provider.json is working fine as I am receiving desired request using it.
Can you try using requestbin ?

**Comment by geeknik** [comment]
Turned out to be a silly local problem. Haha. Thanks for adding this great feature. Do you have a donation box somewhere?

**Comment by proabiral** [comment]
Unfortunately Paypal is not available in my area. You can support my work by sending cryto currencies to any of the addresses below : 

Ethereum : 0xb4692138e8402f9b4f8db4806a81169424627e5b
Ethereum Classic : 0xb4692138e8402f9b4f8db4806a81169424627e5b
LiteCoin : LiM2XkWMb3f1erdxDd8YH3hZc6JwYJ98HC
Bitcoin : 3DhvqaBSexBzU8MmufYvxV8DPoDKYeJSqr
