### ISSUE TITLE
Feature Request: HEAD method

### ISSUE THREAD

**Issue by ghost** [proabiral/inception#33]
in some cases, i would like to check if a path exists, and not reading the full response body. with HEAD this can be achieved. 
would be great if you could implement it :)

**Comment by proabiral** [comment]
Sure, I will be looking at it.

**Comment by ghost** [comment]
I tried adding the HEAD method to providerCreate.html, and created vector.. and it works :) but it didn't catch the response header key properly but catches the key value properly.. 

Would much appreciate if you could add a way to catch response headers with greater/less than feature.. 
for example: content-length < 200

**Comment by proabiral** [comment]
Hi @ikewzer0 ,
Can you please explain this in detail `it didn't catch the response header key properly but catches the key value properly.` ?

**Comment by ghost** [comment]
for example of a HEAD request with curl:
```
~ >>> curl -I https://54.219.180.117/rest/tinymce/1/macro/preview -k                                                                 
HTTP/2 405 
date: Sun, 19 Jan 2020 15:10:59 GMT
x-asen: SEN-12352284
allow: POST,OPTIONS
x-content-type-options: nosniff
```
inception doesn't catch the "x-asen" but if i give the 'SEN' keyword, it works..

**Comment by proabiral** [comment]
hi @ikewzer0 ,
Thanks for raising the issue. Turned out this had nothing to do with HEAD request. 
Curl showed header in lower case as `x-asen`. However, `gorequest` was returning header as `X-Asen`.  As inception was doing case sensitive match, the tool did not catch it.

This has been fixed by changing the behavior of tool to do case in-sensitive match by default. However, command line flag `-caseSensitive` can be used to do case sensitive check as well.

Let me know if you still experience the bug.
